var f,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ca(a,b){if(b){var c=ba;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ca("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this+"";if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});var l=this||self;function m(a){return void 0!==a}function n(a){return"string"==typeof a}function p(a){return"number"==typeof a}function da(){}
function ea(a){a.ha=void 0;a.wa=function(){return a.ha?a.ha:a.ha=new a}}
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function r(a){return"array"==q(a)}function t(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function fa(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ha;return v.apply(null,arguments)}var ia=Date.now||function(){return+new Date};
function w(a,b){function c(){}c.prototype=b.prototype;a.Ca=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ud=function(d,e,g){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};function x(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}w(x,Error);x.prototype.name="CustomError";var ja;function ka(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");x.call(this,c+a[d])}w(ka,x);ka.prototype.name="AssertionError";function la(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var g=d}else a&&(e+=": "+a,g=b);throw new ka(""+e,g||[]);}function y(a,b,c){a||la("",null,b,Array.prototype.slice.call(arguments,2));return a}function ma(a,b){throw new ka("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));}
function z(a,b,c){p(a)||la("Expected number but got %s: %s.",[q(a),a],b,Array.prototype.slice.call(arguments,2));return a}function na(a,b,c){n(a)||la("Expected string but got %s: %s.",[q(a),a],b,Array.prototype.slice.call(arguments,2))};function oa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function pa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function qa(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function ra(a){var b=arguments.length;if(1==b&&r(arguments[0]))return ra.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};function sa(){var a={DEFAULT:0,DARK:1};this.h={};this.za={};if(a)for(var b in a)this.put(b,a[b])}sa.prototype.put=function(a,b){y(!m(this.h[a]));y(!m(this.za[b]));this.h[a]=b;this.za[b]=a};sa.prototype.get=function(a){return this.h[a]};sa.prototype.G=function(){return qa(this.h)};var ta,ua={Sa:"activedescendant",hb:"atomic",ib:"autocomplete",lb:"busy",mb:"checked",rb:"colindex",sb:"controls",wb:"describedby",xb:"disabled",Cb:"dropeffect",Wb:"expanded",Yb:"flowto",Zb:"grabbed",$b:"haspopup",ac:"hidden",dc:"invalid",gc:"label",hc:"labelledby",ic:"level",mc:"live",sc:"multiline",tc:"multiselectable",Ac:"orientation",Bc:"owns",Dc:"posinset",Ec:"pressed",Fa:"readonly",Gc:"relevant",Ic:"required",Jc:"rowindex",Kc:"selected",Mc:"setsize",Sc:"sort",md:"valuemax",nd:"valuemin",od:"valuenow",
pd:"valuetext"};var va=Array.prototype.indexOf?function(a,b){y(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(n(a))return n(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},wa=Array.prototype.forEach?function(a,b,c){y(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},xa=Array.prototype.filter?function(a,b){y(null!=a.length);return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,g=n(a)?a.split(""):a,h=0;h<c;h++)if(h in g){var k=g[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function ya(a){return Array.prototype.concat.apply([],arguments)}function za(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Ba=/&/g,Ca=/</g,Da=/>/g,Ea=/"/g,Fa=/'/g,Ga=/\x00/g,Ha=/[\x00&<>"']/;function Ia(a,b){return a<b?-1:a>b?1:0};var A;a:{var Ja=l.navigator;if(Ja){var Ka=Ja.userAgent;if(Ka){A=Ka;break a}}A=""}function B(a){return-1!=A.indexOf(a)};function C(a,b){this.oa=a===La&&b||"";this.Ha=Ma}C.prototype.L=!0;C.prototype.J=function(){return this.oa};C.prototype.toString=function(){return"Const{"+this.oa+"}"};function Na(a){if(a instanceof C&&a.constructor===C&&a.Ha===Ma)return a.oa;ma("expected object of type Const, got '"+a+"'");return"type_error:Const"}var Ma={},La={};function D(){this.ja=""}D.prototype.L=!0;D.prototype.J=function(){return this.ja.toString()};D.prototype.toString=function(){return"SafeScript{"+this.ja+"}"};D.prototype.w=function(a){this.ja=a;return this};(new D).w("");function E(){this.la=""}E.prototype.L=!0;E.prototype.J=function(){return this.la};E.prototype.toString=function(){return"SafeStyle{"+this.la+"}"};E.prototype.w=function(a){this.la=a;return this};(new E).w("");function F(){this.ka=""}F.prototype.L=!0;F.prototype.J=function(){return this.ka};F.prototype.toString=function(){return"SafeStyleSheet{"+this.ka+"}"};F.prototype.w=function(a){this.ka=a;return this};(new F).w("");function G(){this.ca="";this.Ga=Oa;this.sa=null}G.prototype.Oa=!0;G.prototype.L=!0;G.prototype.J=function(){return this.ca.toString()};G.prototype.toString=function(){return"SafeHtml{"+this.ca+"}"};function Pa(a){if(a instanceof G&&a.constructor===G&&a.Ga===Oa)return a.ca;ma("expected object of type SafeHtml, got '"+a+"' of type "+q(a));return"type_error:SafeHtml"}
function Qa(a){if(a instanceof G)return a;var b="object"==typeof a,c=null;b&&a.Oa&&(c=a.sa);a=b&&a.L?a.J():String(a);Ha.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(Ba,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(Ca,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(Da,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(Ea,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(Fa,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(Ga,"&#0;")));return(new G).w(a,c)}var Oa={};G.prototype.w=function(a,b){this.ca=a;this.sa=b;return this};
(new G).w("<!DOCTYPE html>",0);var Ra=(new G).w("",0);(new G).w("<br>",0);var Ta=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);if(!a.firstChild)return!1;b=a.firstChild.firstChild;a.innerHTML=Pa(Ra);return!b.parentElement});var Ua=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};function H(a){a=m(void 0)?a.toFixed(void 0):String(a);var b=a.indexOf(".");-1==b&&(b=a.length);return Ua("0",Math.max(0,2-b))+a};function Va(a){Va[" "](a);return a}Va[" "]=da;function Wa(a,b){var c=Xa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Ya=B("Opera"),I=B("Trident")||B("MSIE"),Za=B("Edge"),J=B("Gecko")&&!(-1!=A.toLowerCase().indexOf("webkit")&&!B("Edge"))&&!(B("Trident")||B("MSIE"))&&!B("Edge"),$a=-1!=A.toLowerCase().indexOf("webkit")&&!B("Edge");function ab(){var a=l.document;return a?a.documentMode:void 0}var bb;
a:{var cb="",db=function(){var a=A;if(J)return/rv:([^\);]+)(\)|;)/.exec(a);if(Za)return/Edge\/([\d\.]+)/.exec(a);if(I)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if($a)return/WebKit\/(\S+)/.exec(a);if(Ya)return/(?:Version)[ \/]?(\S+)/.exec(a)}();db&&(cb=db?db[1]:"");if(I){var eb=ab();if(null!=eb&&eb>parseFloat(cb)){bb=String(eb);break a}}bb=cb}var fb=bb,Xa={};
function gb(a){return Wa(a,function(){for(var b=0,c=Aa(String(fb)).split("."),d=Aa(String(a)).split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var h=c[g]||"",k=d[g]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Ia(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Ia(0==h[2].length,0==k[2].length)||Ia(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var hb;
hb=l.document&&I?ab():void 0;var ib=!J&&!I||I&&9<=Number(hb)||J&&gb("1.9.1");var jb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function kb(a,b,c){function d(h){h&&b.appendChild(n(h)?a.createTextNode(h):h)}for(var e=1;e<c.length;e++){var g=c[e];!t(g)||u(g)&&0<g.nodeType?d(g):wa(lb(g)?za(g):g,d)}}
function mb(a){y(a,"Node cannot be null or undefined.");return 9==a.nodeType?a:a.ownerDocument||a.document}
function nb(a,b){y(null!=a,"goog.dom.setTextContent expects a non-null value for node");if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(y(a.lastChild));a.firstChild.data=String(b)}else{for(var c;c=a.firstChild;)a.removeChild(c);c=mb(a);a.appendChild(c.createTextNode(String(b)))}}
function lb(a){if(a&&"number"==typeof a.length){if(u(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==q(a))return"function"==typeof a.item}return!1}function ob(){this.P=l.document||document}f=ob.prototype;f.getElementsByTagName=function(a,b){return(b||this.P).getElementsByTagName(String(a))};
f.setProperties=function(a,b){oa(b,function(c,d){c&&"object"==typeof c&&c.L&&(c=c.J());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:jb.hasOwnProperty(d)?a.setAttribute(jb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})};f.createElement=function(a){return this.P.createElement(String(a))};f.createTextNode=function(a){return this.P.createTextNode(String(a))};f.getWindow=function(){var a=this.P;return a.parentWindow||a.defaultView};
f.appendChild=function(a,b){y(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};f.append=function(a,b){kb(mb(a),a,arguments)};f.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
f.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};f.getChildren=function(a){return ib&&void 0!=a.children?a.children:xa(a.childNodes,function(b){return 1==b.nodeType})};f.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};ra("A AREA BUTTON HEAD INPUT LINK MENU META OPTGROUP OPTION PROGRESS STYLE SELECT SOURCE TEXTAREA TITLE TRACK".split(" "));
function pb(a,b,c){r(c)&&(c=c.join(" "));var d=qb(b);""===c||void 0==c?(ta||(ta={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=ta,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function qb(a){y(a,"ARIA attribute cannot be empty.");a:{for(b in ua)if(ua[b]==a){var b=!0;break a}b=!1}y(b,"No such ARIA attribute "+a);return"aria-"+a};function K(){this.fa=this.fa}K.prototype.fa=!1;K.prototype.isDisposed=function(){return this.fa};function rb(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.ma=!1}rb.prototype.stopPropagation=function(){this.ma=!0};rb.prototype.preventDefault=function(){this.defaultPrevented=!0};var sb=Object.freeze||function(a){return a};var tb=!I||9<=Number(hb),ub=I&&!gb("9"),vb=function(){if(!l.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{l.addEventListener("test",da,b),l.removeEventListener("test",da,b)}catch(c){}return a}();function L(a,b){rb.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.R=null;a&&this.init(a,b)}w(L,rb);var wb=sb({2:"touch",3:"pen",4:"mouse"});
L.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(J){a:{try{Va(b.nodeName);var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=
d.screenY||0):(this.offsetX=$a||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=$a||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=
a.pointerId||0;this.pointerType=n(a.pointerType)?a.pointerType:wb[a.pointerType]||"";this.state=a.state;this.R=a;a.defaultPrevented&&this.preventDefault()};L.prototype.stopPropagation=function(){L.Ca.stopPropagation.call(this);this.R.stopPropagation?this.R.stopPropagation():this.R.cancelBubble=!0};
L.prototype.preventDefault=function(){L.Ca.preventDefault.call(this);var a=this.R;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ub)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var xb="closure_listenable_"+(1E6*Math.random()|0),yb=0;function zb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.ga=e;this.key=++yb;this.removed=this.da=!1}function Ab(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.ga=null};function Bb(a){this.src=a;this.i={};this.V=0}f=Bb.prototype;f.add=function(a,b,c,d,e){var g=a.toString();a=this.i[g];a||(a=this.i[g]=[],this.V++);var h=Cb(a,b,d,e);-1<h?(b=a[h],c||(b.da=!1)):(b=new zb(b,this.src,g,!!d,e),b.da=c,a.push(b));return b};f.remove=function(a,b,c,d){a=a.toString();if(!(a in this.i))return!1;var e=this.i[a];b=Cb(e,b,c,d);return-1<b?(Ab(e[b]),y(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.i[a],this.V--),!0):!1};
function Db(a,b){var c=b.type;if(c in a.i){var d=a.i[c],e=va(d,b),g;if(g=0<=e)y(null!=d.length),Array.prototype.splice.call(d,e,1);g&&(Ab(b),0==a.i[c].length&&(delete a.i[c],a.V--))}}f.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.i)if(!a||c==a){for(var d=this.i[c],e=0;e<d.length;e++)++b,Ab(d[e]);delete this.i[c];this.V--}return b};f.La=function(a,b,c,d){a=this.i[a.toString()];var e=-1;a&&(e=Cb(a,b,c,d));return-1<e?a[e]:null};
f.hasListener=function(a,b){var c=m(a),d=c?a.toString():"",e=m(b);return pa(this.i,function(g){for(var h=0;h<g.length;++h)if(!(c&&g[h].type!=d||e&&g[h].capture!=b))return!0;return!1})};function Cb(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.removed&&g.listener==b&&g.capture==!!c&&g.ga==d)return e}return-1};var Eb="closure_lm_"+(1E6*Math.random()|0),Fb={},Gb=0;function Hb(a,b,c,d,e){if(d&&d.once)Ib(a,b,c,d,e);else if(r(b))for(var g=0;g<b.length;g++)Hb(a,b[g],c,d,e);else c=Jb(c),a&&a[xb]?a.listen(b,c,u(d)?!!d.capture:!!d,e):Kb(a,b,c,!1,d,e)}
function Kb(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var h=u(e)?!!e.capture:!!e,k=Lb(a);k||(a[Eb]=k=new Bb(a));c=k.add(b,c,d,h,g);if(!c.proxy){d=Mb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)vb||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Ob(b.toString()),d);else if(a.addListener&&a.removeListener)y("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");
Gb++}}function Mb(){var a=Pb,b=tb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Ib(a,b,c,d,e){if(r(b))for(var g=0;g<b.length;g++)Ib(a,b[g],c,d,e);else c=Jb(c),a&&a[xb]?a.ua.add(String(b),c,!0,u(d)?!!d.capture:!!d,e):Kb(a,b,c,!0,d,e)}function Qb(a,b,c,d,e){if(r(b))for(var g=0;g<b.length;g++)Qb(a,b[g],c,d,e);else d=u(d)?!!d.capture:!!d,c=Jb(c),a&&a[xb]?a.ua.remove(String(b),c,d,e):a&&(a=Lb(a))&&(b=a.La(b,c,d,e))&&Rb(b)}
function Rb(a){if(!p(a)&&a&&!a.removed){var b=a.src;if(b&&b[xb])Db(b.ua,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Ob(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Gb--;(c=Lb(b))?(Db(c,a),0==c.V&&(c.src=null,b[Eb]=null)):Ab(a)}}}function Ob(a){return a in Fb?Fb[a]:Fb[a]="on"+a}
function Sb(a,b,c,d){var e=!0;if(a=Lb(a))if(b=a.i[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.removed&&(g=Tb(g,d),e=e&&!1!==g)}return e}function Tb(a,b){var c=a.listener,d=a.ga||a.src;a.da&&Rb(a);return c.call(d,b)}
function Pb(a,b){if(a.removed)return!0;if(!tb){if(!b)a:{b=["window","event"];for(var c=l,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new L(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.currentTarget;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.ma&&0<=e;e--){b.currentTarget=d[e];var g=Sb(d[e],a,!0,b);c=c&&g}for(e=0;!b.ma&&e<d.length;e++)b.currentTarget=
d[e],g=Sb(d[e],a,!1,b),c=c&&g}return c}return Tb(a,new L(b,this))}function Lb(a){a=a[Eb];return a instanceof Bb?a:null}var Ub="__closure_events_fn_"+(1E9*Math.random()>>>0);function Jb(a){y(a,"Listener can not be null.");if("function"==q(a))return a;y(a.handleEvent,"An object listener must have handleEvent method.");a[Ub]||(a[Ub]=function(b){return a.handleEvent(b)});return a[Ub]};function Vb(a,b){if("function"!=q(a))if(a&&"function"==typeof a.handleEvent)a=v(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:l.setTimeout(a,b||0)};function Wb(a){K.call(this);this.ta=a||ja||(ja=new ob);this.Aa={}}w(Wb,K);function Xb(a,b,c){var d=Yb(a,c||"polite");nb(d,"");Vb(function(){nb(d,b)},1)}function Yb(a,b){var c=a.Aa[b];if(c)return c.removeAttribute(qb("hidden")),c;c=a.ta.createElement("DIV");c.style.position="absolute";c.style.top="-1000px";c.style.height="1px";c.style.overflow="hidden";pb(c,"live",b);pb(c,"atomic","true");a.ta.P.body.appendChild(c);return a.Aa[b]=c};function Zb(){this.Ja=new Wb}ea(Zb);Zb.prototype.speak=function(a,b){Xb(this.Ja,a,b)};var $b={Ra:"n_amt",Ta:"n_afoiu",Va:"n_age",Wa:"n_ades",Xa:"n_k",fb:"n_u",Ya:"n_r",Za:"n_p",$a:"n_ars",ab:"n_s",bb:"n_ss",cb:"n_ats",eb:"n_atas",gb:"n_v",jb:"n_bi",kb:"n_bl",nb:"n_cc",ob:"n_c",pb:"n_cp",qb:"n_csbs",vb:"n_dt",yb:"n_deau",zb:"n_detl",Ab:"n_dshl",Bb:"n_dssl",Db:"n_eau",Eb:"n_ecil",Fb:"n_ecpde",Gb:"n_edmp",Hb:"n_edmu",Ib:"n_edtt",Jb:"n_edlh",Kb:"n_eema",Lb:"n_eil",Mb:"n_eliw",Nb:"n_em",Ob:"n_eod",Pb:"n_eoros",Qb:"n_eop",Rb:"n_eon",Sb:"n_ep",Tb:"n_esiv",Xb:"n_fpae",bc:"n_imb",cc:"n_imp",
ec:"n_ica",fc:"n_j",kc:"n_lil",lc:"n_lilt",nc:"n_mpak",oc:"n_mpau",pc:"n_mil",qc:"n_iu",yc:"n_nmri",wc:"n_nib",xc:"n_nmb",Fa:"n_ro",Hc:"n_rau",Lc:"n_ses",Qc:"docs-show_debug_info",Rc:"n_scp",Zc:"n_sit",jc:"n_lcu",zc:"n_oe",Cc:"n_pau",$c:"n_t",cd:"n_ton",ad:"n_tak",bd:"n_tipe",dd:"n_taau",ed:"n_tcu",fd:"n_tcur",hd:"n_tmd",jd:"n_ur",kd:"n_ugat",ld:"n_uo",USER:"n_us",qd:"n_wfp",rd:"n_wcv"};var ac="StopIteration"in l?l.StopIteration:{message:"StopIteration",stack:""};function bc(){}bc.prototype.next=function(){throw ac;};bc.prototype.Ia=function(){return this};function cc(a,b){this.h={};this.g=[];this.W=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)}f=cc.prototype;f.C=function(){dc(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};f.G=function(){dc(this);return this.g.concat()};f.O=function(a){return M(this.h,a)};f.clear=function(){this.h={};this.W=this.c=this.g.length=0};
f.remove=function(a){return M(this.h,a)?(delete this.h[a],this.c--,this.W++,this.g.length>2*this.c&&dc(this),!0):!1};function dc(a){if(a.c!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];M(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.c!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],M(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}}f.get=function(a,b){return M(this.h,a)?this.h[a]:b};f.set=function(a,b){M(this.h,a)||(this.c++,this.g.push(a),this.W++);this.h[a]=b};
f.addAll=function(a){if(a instanceof cc)for(var b=a.G(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};f.forEach=function(a,b){for(var c=this.G(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};f.clone=function(){return new cc(this)};f.Ia=function(a){dc(this);var b=0,c=this.W,d=this,e=new bc;e.next=function(){if(c!=d.W)throw Error("The map has changed since the iterator was created");if(b>=d.g.length)throw ac;var g=d.g[b++];return a?g:d.h[g]};return e};
function M(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function ec(a){if(a.C&&"function"==typeof a.C)return a.C();if(n(a))return a.split("");if(t(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function fc(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(t(a)||n(a))wa(a,b,c);else{if(a.G&&"function"==typeof a.G)var d=a.G();else if(a.C&&"function"==typeof a.C)d=void 0;else if(t(a)||n(a)){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else d=qa(a);e=ec(a);g=e.length;for(var h=0;h<g;h++)b.call(c,e[h],d&&d[h],a)}};var gc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function hc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function N(a,b){this.F=this.K=this.H="";this.M=null;this.I=this.D="";this.m=this.Pa=!1;if(a instanceof N){this.m=m(b)?b:a.m;ic(this,a.H);var c=a.K;O(this);this.K=c;c=a.F;O(this);this.F=c;jc(this,a.M);c=a.D;O(this);this.D=c;kc(this,a.s.clone());a=a.I;O(this);this.I=a}else a&&(c=String(a).match(gc))?(this.m=!!b,ic(this,c[1]||"",!0),a=c[2]||"",O(this),this.K=P(a),a=c[3]||"",O(this),this.F=P(a,!0),jc(this,c[4]),a=c[5]||"",O(this),this.D=P(a,!0),kc(this,c[6]||"",!0),a=c[7]||"",O(this),this.I=P(a)):(this.m=
!!b,this.s=new Q(null,this.m))}f=N.prototype;f.toString=function(){var a=[],b=this.H;b&&a.push(R(b,lc,!0),":");var c=this.F;if(c||"file"==b)a.push("//"),(b=this.K)&&a.push(R(b,lc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.M,null!=c&&a.push(":",String(c));if(c=this.D)this.F&&"/"!=c.charAt(0)&&a.push("/"),a.push(R(c,"/"==c.charAt(0)?mc:nc,!0));(c=this.s.toString())&&a.push("?",c);(c=this.I)&&a.push("#",R(c,oc));return a.join("")};
f.resolve=function(a){var b=this.clone(),c=!!a.H;c?ic(b,a.H):c=!!a.K;if(c){var d=a.K;O(b);b.K=d}else c=!!a.F;c?(d=a.F,O(b),b.F=d):c=null!=a.M;d=a.D;if(c)jc(b,a.M);else if(c=!!a.D){if("/"!=d.charAt(0))if(this.F&&!this.D)d="/"+d;else{var e=b.D.lastIndexOf("/");-1!=e&&(d=b.D.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],h=0;h<e.length;){var k=e[h++];"."==k?d&&h==e.length&&g.push(""):".."==k?((1<g.length||
1==g.length&&""!=g[0])&&g.pop(),d&&h==e.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=e}c?(O(b),b.D=d):c=""!==a.s.toString();c?kc(b,a.s.clone()):c=!!a.I;c&&(a=a.I,O(b),b.I=a);return b};f.clone=function(){return new N(this)};function ic(a,b,c){O(a);a.H=c?P(b,!0):b;a.H&&(a.H=a.H.replace(/:$/,""))}function jc(a,b){O(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.M=b}else a.M=null}
function kc(a,b,c){O(a);b instanceof Q?(a.s=b,a.s.na(a.m)):(c||(b=R(b,pc)),a.s=new Q(b,a.m))}f.getQuery=function(){return this.s.toString()};f.removeParameter=function(a){O(this);this.s.remove(a);return this};function O(a){if(a.Pa)throw Error("Tried to modify a read-only Uri");}f.na=function(a){this.m=a;this.s&&this.s.na(a)};function P(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}
function R(a,b,c){return n(a)?(a=encodeURI(a).replace(b,qc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function qc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var lc=/[#\/\?@]/g,nc=/[#\?:]/g,mc=/[#\?]/g,pc=/[#\?@]/g,oc=/#/g;function Q(a,b){this.c=this.b=null;this.j=a||null;this.m=!!b}function S(a){a.b||(a.b=new cc,a.c=0,a.j&&hc(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=Q.prototype;
f.add=function(a,b){S(this);this.j=null;a=T(this,a);var c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.c=z(this.c)+1;return this};f.remove=function(a){S(this);a=T(this,a);return this.b.O(a)?(this.j=null,this.c=z(this.c)-this.b.get(a).length,this.b.remove(a)):!1};f.clear=function(){this.b=this.j=null;this.c=0};f.O=function(a){S(this);a=T(this,a);return this.b.O(a)};f.forEach=function(a,b){S(this);this.b.forEach(function(c,d){wa(c,function(e){a.call(b,e,d,this)},this)},this)};
f.G=function(){S(this);for(var a=this.b.C(),b=this.b.G(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};f.C=function(a){S(this);var b=[];if(n(a))this.O(a)&&(b=ya(b,this.b.get(T(this,a))));else{a=this.b.C();for(var c=0;c<a.length;c++)b=ya(b,a[c])}return b};f.set=function(a,b){S(this);this.j=null;a=T(this,a);this.O(a)&&(this.c=z(this.c)-this.b.get(a).length);this.b.set(a,[b]);this.c=z(this.c)+1;return this};
f.get=function(a,b){if(!a)return b;a=this.C(a);return 0<a.length?String(a[0]):b};f.toString=function(){if(this.j)return this.j;if(!this.b)return"";for(var a=[],b=this.b.G(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.C(d);for(var g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}}return this.j=a.join("&")};f.clone=function(){var a=new Q;a.j=this.j;this.b&&(a.b=this.b.clone(),a.c=this.c);return a};
function T(a,b){b=String(b);a.m&&(b=b.toLowerCase());return b}f.na=function(a){a&&!this.m&&(S(this),this.j=null,this.b.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.j=null,this.b.set(T(this,d),za(b)),this.c=z(this.c)+b.length))},this));this.m=a};f.extend=function(a){for(var b=0;b<arguments.length;b++)fc(arguments[b],function(c,d){this.add(d,c)},this)};var rc=B("Safari")&&!((B("Chrome")||B("CriOS"))&&!B("Edge")||B("Coast")||B("Opera")||B("Edge")||B("Edg/")||B("OPR")||B("Firefox")||B("FxiOS")||B("Silk")||B("Android"))&&!(B("iPhone")&&!B("iPod")&&!B("iPad")||B("iPad")||B("iPod"));function sc(){this.va={};tc(this,l._docs_flag_initialData||{});uc(this)}function tc(a,b){oa($b,function(c){m(b[c])&&(a.va[c]=b[c])})}function uc(a){var b={};(new N(window.location.href)).s.forEach(function(c,d){b[d]=c});tc(a,b)}ea(sc);var vc={Vb:["BC","AD"],Ub:["Before Christ","Anno Domini"],uc:"JFMAMJJASOND".split(""),Uc:"JFMAMJJASOND".split(""),rc:"January February March April May June July August September October November December".split(" "),Tc:"January February March April May June July August September October November December".split(" "),Nc:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),Wc:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),sd:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Yc:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Pc:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Xc:"Sun Mon Tue Wed Thu Fri Sat".split(" "),vc:"SMTWTFS".split(""),Vc:"SMTWTFS".split(""),Oc:["Q1","Q2","Q3","Q4"],Fc:["1st quarter","2nd quarter","3rd quarter","4th quarter"],Ua:["AM","PM"],tb:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],gd:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],ub:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],Da:6,td:[5,6],Ea:5},wc=vc;
wc=vc;function U(a,b,c,d,e,g){n(a)?(this.B="y"==a?b:0,this.A="m"==a?b:0,this.v="d"==a?b:0,this.l="h"==a?b:0,this.o="n"==a?b:0,this.u="s"==a?b:0):(this.B=a||0,this.A=b||0,this.v=c||0,this.l=d||0,this.o=e||0,this.u=g||0)}
U.prototype.U=function(a){var b=Math.min(this.B,this.A,this.v,this.l,this.o,this.u),c=Math.max(this.B,this.A,this.v,this.l,this.o,this.u);if(0>b&&0<c)return null;if(!a&&0==b&&0==c)return"PT0S";c=[];0>b&&c.push("-");c.push("P");(this.B||a)&&c.push(Math.abs(this.B)+"Y");(this.A||a)&&c.push(Math.abs(this.A)+"M");(this.v||a)&&c.push(Math.abs(this.v)+"D");if(this.l||this.o||this.u||a)c.push("T"),(this.l||a)&&c.push(Math.abs(this.l)+"H"),(this.o||a)&&c.push(Math.abs(this.o)+"M"),(this.u||a)&&c.push(Math.abs(this.u)+
"S");return c.join("")};U.prototype.clone=function(){return new U(this.B,this.A,this.v,this.l,this.o,this.u)};U.prototype.add=function(a){this.B+=a.B;this.A+=a.A;this.v+=a.v;this.l+=a.l;this.o+=a.o;this.u+=a.u};function V(a,b,c){p(a)?(this.a=xc(a,b||0,c||1),yc(this,c||1)):u(a)?(this.a=xc(a.getFullYear(),a.getMonth(),a.getDate()),yc(this,a.getDate())):(this.a=new Date(ia()),a=this.a.getDate(),this.a.setHours(0),this.a.setMinutes(0),this.a.setSeconds(0),this.a.setMilliseconds(0),yc(this,a))}
function xc(a,b,c){b=new Date(a,b,c);0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b}f=V.prototype;f.Y=wc.Da;f.Z=wc.Ea;f.clone=function(){var a=new V(this.a);a.Y=this.Y;a.Z=this.Z;return a};f.getFullYear=function(){return this.a.getFullYear()};f.getYear=function(){return this.getFullYear()};f.getMonth=function(){return this.a.getMonth()};f.getDate=function(){return this.a.getDate()};f.getTime=function(){return this.a.getTime()};f.getDay=function(){return this.a.getDay()};
f.getUTCFullYear=function(){return this.a.getUTCFullYear()};f.getUTCMonth=function(){return this.a.getUTCMonth()};f.getUTCDate=function(){return this.a.getUTCDate()};f.getUTCDay=function(){return this.a.getDay()};f.getUTCHours=function(){return this.a.getUTCHours()};f.getUTCMinutes=function(){return this.a.getUTCMinutes()};f.getTimezoneOffset=function(){return this.a.getTimezoneOffset()};f.set=function(a){this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate())};f.setFullYear=function(a){this.a.setFullYear(a)};
f.setYear=function(a){this.setFullYear(a)};f.setMonth=function(a){this.a.setMonth(a)};f.setDate=function(a){this.a.setDate(a)};f.setTime=function(a){this.a.setTime(a)};f.setUTCFullYear=function(a){this.a.setUTCFullYear(a)};f.setUTCMonth=function(a){this.a.setUTCMonth(a)};f.setUTCDate=function(a){this.a.setUTCDate(a)};
f.add=function(a){if(a.B||a.A){var b=this.getMonth()+a.A+12*a.B,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.v&&(a=new Date((new Date(this.getYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.v),this.setDate(1),this.setFullYear(a.getFullYear()),this.setMonth(a.getMonth()),
this.setDate(a.getDate()),yc(this,a.getDate()))};f.U=function(a){return[this.getFullYear(),H(this.getMonth()+1),H(this.getDate())].join(a?"-":"")+""};f.toString=function(){return this.U()};function yc(a,b){a.getDate()!=b&&a.a.setUTCHours(a.a.getUTCHours()+(a.getDate()<b?1:-1))}f.valueOf=function(){return this.a.valueOf()};function W(a,b,c,d,e,g,h){this.a=p(a)?new Date(a,b||0,c||1,d||0,e||0,g||0,h||0):new Date(a&&a.getTime?a.getTime():ia())}w(W,V);f=W.prototype;f.getHours=function(){return this.a.getHours()};
f.getMinutes=function(){return this.a.getMinutes()};f.getSeconds=function(){return this.a.getSeconds()};f.getMilliseconds=function(){return this.a.getMilliseconds()};f.getUTCDay=function(){return this.a.getUTCDay()};f.getUTCHours=function(){return this.a.getUTCHours()};f.getUTCMinutes=function(){return this.a.getUTCMinutes()};f.getUTCSeconds=function(){return this.a.getUTCSeconds()};f.getUTCMilliseconds=function(){return this.a.getUTCMilliseconds()};f.setHours=function(a){this.a.setHours(a)};
f.setMinutes=function(a){this.a.setMinutes(a)};f.setSeconds=function(a){this.a.setSeconds(a)};f.setMilliseconds=function(a){this.a.setMilliseconds(a)};f.setUTCHours=function(a){this.a.setUTCHours(a)};f.setUTCMinutes=function(a){this.a.setUTCMinutes(a)};f.setUTCSeconds=function(a){this.a.setUTCSeconds(a)};f.setUTCMilliseconds=function(a){this.a.setUTCMilliseconds(a)};
f.add=function(a){V.prototype.add.call(this,a);a.l&&this.setUTCHours(this.a.getUTCHours()+a.l);a.o&&this.setUTCMinutes(this.a.getUTCMinutes()+a.o);a.u&&this.setUTCSeconds(this.a.getUTCSeconds()+a.u)};f.U=function(a){var b=V.prototype.U.call(this,a);return a?b+" "+H(this.getHours())+":"+H(this.getMinutes())+":"+H(this.getSeconds()):b+"T"+H(this.getHours())+H(this.getMinutes())+H(this.getSeconds())};f.toString=function(){return this.U()};
f.clone=function(){var a=new W(this.a);a.Y=this.Y;a.Z=this.Z;return a};var zc=null,Ac=null,Bc=J||$a&&!rc||Ya||!rc&&!I&&"function"==typeof l.atob;function Cc(a,b){function c(Oc){for(;d<a.length;){var Sa=a.charAt(d++),Nb=Ac[Sa];if(null!=Nb)return Nb;if(!/^[\s\xa0]*$/.test(Sa))throw Error("Unknown base64 encoding at char: "+Sa);}return Oc}Dc();for(var d=0;;){var e=c(-1),g=c(0),h=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|g>>4);64!=h&&(b(g<<4&240|h>>2),64!=k&&b(h<<6&192|k))}}
function Dc(){if(!zc){zc={};Ac={};for(var a=0;65>a;a++)zc[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a),Ac[zc[a]]=a,62<=a&&(Ac["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a)]=a)}};function Ec(){};function Fc(){new DataView(new ArrayBuffer(8))}w(Fc,Ec);new Fc;function X(a,b,c){K.call(this);this.aa=a;this.ia=b||0;this.Na=c;this.ea=v(this.X,this)}w(X,K);X.prototype.S=0;X.prototype.start=function(a){this.stop();this.S=Vb(this.ea,m(a)?a:this.ia)};X.prototype.stop=function(){0!=this.S&&l.clearTimeout(this.S);this.S=0};X.prototype.X=function(){this.S=0;this.aa&&this.aa.call(this.Na)};function Gc(a,b,c){K.call(this);this.aa=null!=c?v(a,c):a;this.ia=b;this.ea=v(this.Qa,this);this.pa=[]}w(Gc,K);f=Gc.prototype;f.T=!1;f.ba=0;f.N=null;f.stop=function(){this.N&&(l.clearTimeout(this.N),this.N=null,this.T=!1,this.pa=[])};f.pause=function(){this.ba++};f.resume=function(){this.ba--;this.ba||!this.T||this.N||(this.T=!1,this.X())};f.Qa=function(){this.N=null;this.T&&!this.ba&&(this.T=!1,this.X())};f.X=function(){this.N=Vb(this.ea,this.ia);this.aa.apply(null,this.pa)};var Hc=new W,Ic=new V;new Gc(function(){var a=sc.wa().va.n_tmd;a=isNaN(a)?0:Number(a);Hc=new W;Hc.add(new U("d",-1*a))},6E4);var Jc=new X(function(){Ic=new V;Ic.add(new U("d",2));Jc.start()},864E5);new sa;(function(a,b){if(Bc&&!b)return l.atob(a);var c="";Cc(a,function(d){c+=String.fromCharCode(d)});return c})("bGFiZWxz");Object.freeze("annotationsGroup isArchived isDirty isPinned lastSyncedText parentServerId reminder baseVersion serverId shareState roleInfo showAvailableInShoppingNotification timestamps".split(" "));/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var Kc={vd:!0};function Y(){throw Error("Do not instantiate directly");}Y.prototype.ra=null;Y.prototype.getContent=function(){return this.content};Y.prototype.toString=function(){return this.content};function Lc(){Y.call(this)}w(Lc,Y);Lc.prototype.Ka=Kc;var Mc=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.ra=d);return c}}(Lc);function Nc(){return Mc('<iframe frameborder="0" style=" height: 438px; margin: 0px; padding: 0px; position: fixed; right: 5px; top: 5px; width: 370px; z-index: 2147483647;"></iframe>')}Nc.wd="notes.browseraction.soy.injects.injectedIframe";var Pc=/^<(body|caption|col|colgroup|head|html|tr|td|th|tbody|thead|tfoot)>/i,Qc={};function Rc(){this.f=null;this.$=!1;this.qa="";this.ya();Hb(document,"mousedown",this.xa,void 0,this);var a={};a.selectedText=window.getSelection().toString();for(var b=document.getElementsByTagName("META"),c=0,d;d=b[c];c++)if("og:image"==d.getAttribute("property")){a.imageUrl=d.getAttribute("content");break}if(!a.imageUrl){b=0;d=document.getElementsByTagName("IMG");c=0;for(var e;e=d[c];c++){var g=e.naturalWidth||e.width,h=e.naturalHeight||e.height;if(128<=h&&128<=g&&h*g>b){b=h*g;var k=e.src}}k&&
(a.imageUrl=k)}a.imageUrl&&(c=a.imageUrl,c=c instanceof N?c.clone():new N(c,void 0),c.H||ic(c,"http"),a.imageUrl=c.toString());Z(this,"pageScrape",a);this.Ba=v(this.Ma,this);chrome.runtime.onMessage.addListener(this.Ba)}function Sc(a){a.f=null;Qb(document,"mousedown",v(a.xa,a),void 0,a);chrome.runtime.onMessage.removeListener(a.Ba);a.$=!0}function Z(a,b,c){if(!a.$)try{chrome.runtime.sendMessage(chrome.runtime.id,{type:b,value:c},void 0)}catch(d){Sc(a)}}
function Tc(a,b,c){if(!a.$)try{chrome.runtime.sendMessage(chrome.runtime.id,{type:"trackEvent",value:{action:c,category:b,label:void 0,value:void 0}},void 0)}catch(d){Sc(a)}}
Rc.prototype.Ma=function(a,b,c){if(u(a)&&!this.$)switch(a.type){case "appHeightChange":this.f&&(this.f.style.height=a.value);break;case "dispose":Sc(this);break;case "finishHide":this.f&&Uc(this,!1);break;case "selectedTextRequest":c(window.getSelection().toString());break;case "speakMessage":Zb.wa().speak(a.value);break;case "show":this.f&&(a="none"==this.f.style.display,Uc(this,!0),c(a));break;case "toggleVisibility":this.f?"none"==this.f.style.display?(Uc(this,!0),this.f.contentWindow.focus(),
Z(this,"show"),Tc(this,"Popup re-opened","Toggled button clicked")):(Z(this,"startHide"),Tc(this,"Popup closed","Toggled from the toolbar"),Z(this,"impression",9204)):Tc(this,"Error","toggle visibility called with no iframe present")}};
Rc.prototype.ya=function(){if("interactive"!=document.readyState&&"complete"!=document.readyState)Hb(document,"DOMContentLoaded",this.ya,void 0,this);else{y(Nc,"Soy template may not be null.");var a=Nc(Qc,void 0,void 0);var b=(ja||(ja=new ob)).createElement("DIV");if(u(a))if(a instanceof Y){if(a.Ka!==Kc)throw Error("Sanitized content was not of kind HTML.");var c=a.toString();a=a.ra;var d=new C(La,"Soy SanitizedContent of kind HTML produces SafeHtml-contract-compliant value.");na(Na(d),"must provide justification");
y(!/^[\s\xa0]*$/.test(Na(d)),"must provide non-empty justification");c=(new G).w(c,a||null)}else ma("Soy template output is unsafe for use as HTML: "+a),c=Qa("zSoyz");else c=Qa(String(a));a=c.J();d=a.match(Pc);y(!d,"This template starts with a %s, which cannot be a child of a <div>, as required by soy internals. Consider using goog.soy.renderElement instead.\nTemplate output: %s",d&&d[0],a);if(Ta())for(;b.lastChild;)b.removeChild(b.lastChild);b.innerHTML=Pa(c);1==b.childNodes.length&&(c=b.firstChild,
1==c.nodeType&&(b=c));this.f=b;this.qa=this.f.style.cssText;this.f.id="keep-popup-frame";this.f.src=chrome.extension.getURL("index.html");document.body.appendChild(this.f);Uc(this,!0);this.f.contentWindow.focus()}};function Uc(a,b){a.f.style.cssText=a.qa+" display: "+(b?"block !important;":"none")}Rc.prototype.xa=function(a){0==a.button&&this.f&&"none"!=this.f.style.display&&(Z(this,"startHide"),Tc(this,"Popup closed","Clicked out"),Z(this,"impression",9203))};new Rc;
